Store upgrade
Indaym/Web-Indaym pull request #51
Opened 2017-12-15 16:31 UTC by djavrell

2017-12-15 16:34 UTC, NicolasDelahaigue commented
Ne pas oublier à renommer les fichier css en scss je pense à store.component et gameCard aussi

2017-12-15 16:35 UTC, NicolasDelahaigue requested changes
Ne pas oublier à renommer les fichier css en scss je pense à store et gameCard aussi

2018-01-05 18:25 UTC, djavrell commented
quand ta Pr sera merge dans la mienne ouai, mais pas avant

2018-01-05 18:26 UTC, NicolasDelahaigue commented
La présence des fichiers scss sont déjà sur develop

2018-01-05 18:35 UTC, djavrell commented
ouai, bah j'ai pas encore rebase sur dev, je ferais ça en même temps, sinon il va pas aimer là

2018-01-05 18:53 UTC, djavrell commented
content ?

2018-01-05 18:55 UTC, NicolasDelahaigue commented
si tout marche comme il faut oui :)

2018-01-05 18:55 UTC, NicolasDelahaigue approved these changes

2018-01-10 20:17 UTC, merged